# Generated by Django 4.1.7 on 2023-03-23 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport_posts', '0002_post_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Коментарий', 'verbose_name_plural': 'Коментарии'},
        ),
    ]
