# Generated by Django 4.1.7 on 2023-03-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='phone',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
