# Generated by Django 4.1.7 on 2023-03-19 13:58

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('order1', '0002_alter_orders_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='BY', verbose_name='Телефон'),
        ),
    ]
